### ISSUE TITLE
As a developer, I would like to have the widgets and the notations migrated to the new platform to be used in the new content

### ISSUE THREAD

**Issue by Tansito** [Qiskit/saiba#58] opened 2022-08-12 11:39 UTC
### Background

Due to the migration we will need to move our widgets and the notations from platypus to saiba using the new structure.

### Goal

Migrate widgets, glossary and notations to the new platform.

### Acceptance criteria

- [ ] Widgets migrated
- [ ] Glossary migrated
- [ ] Notations migrated

### Tasks

The tasks for this feature are being managed through this [milestone](https://github.com/Qiskit/saiba/milestone/12) divided in the next tasks:

- TODO: it will be a task per widget here and in the milestone
- https://github.com/Qiskit/saiba/issues/54
- https://github.com/Qiskit/saiba/issues/64
- https://github.com/Qiskit/saiba/issues/65

**Comment by eddybrando** [comment] 2022-12-06 13:03
Duplicate of:

- https://github.com/Qiskit/saiba/issues/54
- https://github.com/Qiskit/saiba/issues/180

**Closed by eddybrando** 2022-12-06 13:03 UTC
Labels: story
